name: CI Quality Gate

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with Ruff
      run: |
        ruff check .
        ruff format --check .

    - name: Run Pytest with Coverage
      run: |
        pytest --cov=src --cov-report=term-missing --cov-report=xml --cov-report=html --cov-fail-under=60

    - name: Upload Coverage Reports
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

    - name: Run Evaluation Harness
      run: |
        # Run evaluation harness - it will automatically detect if API is available
        # and use mock responses if needed (for CI when API server is not running)
        python scripts/run_evaluation.py