name: CI Quality Gate

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - production

env:
  TF_VERSION: '1.5.0'
  TF_WORKING_DIR: './terraform'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with Ruff
      run: |
        ruff check .
        ruff format --check .

    - name: Run Pytest with Coverage
      run: |
        pytest --cov=src --cov-report=term-missing --cov-report=xml --cov-report=html --cov-fail-under=60

    - name: Upload Coverage Reports
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

    - name: Run Evaluation Harness
      run: |
        # Run evaluation harness - it will automatically detect if API is available
        # and use mock responses if needed (for CI when API server is not running)
        python scripts/run_evaluation.py

  terraform-validate:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    steps:
    - uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Check AWS Credentials
      run: |
        if [ -z "$AWS_ACCESS_KEY_ID" ] || [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
          echo "❌ AWS credentials not found in repository secrets."
          echo "Please configure the following secrets in your GitHub repository:"
          echo "  - AWS_ACCESS_KEY_ID"
          echo "  - AWS_SECRET_ACCESS_KEY"
          echo ""
          echo "To add these secrets:"
          echo "1. Go to your repository Settings > Secrets and variables > Actions"
          echo "2. Click 'New repository secret'"
          echo "3. Add AWS_ACCESS_KEY_ID with your AWS access key"
          echo "4. Add AWS_SECRET_ACCESS_KEY with your AWS secret key"
          exit 1
        fi
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Verify Terraform Directory
      run: |
        if [ ! -d "${{ env.TF_WORKING_DIR }}" ]; then
          echo "❌ Terraform directory '${{ env.TF_WORKING_DIR }}' not found!"
          echo "Expected terraform files in: ${{ env.TF_WORKING_DIR }}/"
          ls -la
          exit 1
        fi
        echo "✅ Terraform directory found: ${{ env.TF_WORKING_DIR }}"

    - name: Bootstrap Terraform Backend
      working-directory: ${{ env.TF_WORKING_DIR }}
      run: |
        echo "🚀 Bootstrapping Terraform backend resources..."
        # Initialize with local backend for bootstrap
        terraform init -backend=false
        # Apply bootstrap configuration to create S3 bucket and DynamoDB table
        terraform apply -target=aws_s3_bucket.terraform_state -target=aws_s3_bucket_versioning.terraform_state -target=aws_s3_bucket_server_side_encryption_configuration.terraform_state -target=aws_dynamodb_table.terraform_locks -auto-approve
        echo "✅ Backend resources created successfully"

    - name: Terraform Init
      working-directory: ${{ env.TF_WORKING_DIR }}
      run: terraform init

    - name: Terraform Validate
      working-directory: ${{ env.TF_WORKING_DIR }}
      run: terraform validate

    - name: Terraform Plan
      working-directory: ${{ env.TF_WORKING_DIR }}
      run: terraform plan -out=tfplan

  deploy-staging:
    runs-on: ubuntu-latest
    needs: terraform-validate
    if: (github.ref == 'refs/heads/main' && github.event_name != 'workflow_dispatch') || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'staging')
    environment: staging
    steps:
    - uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Check AWS Credentials
      run: |
        if [ -z "$AWS_ACCESS_KEY_ID" ] || [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
          echo "❌ AWS credentials not found in repository secrets."
          echo "Please configure the following secrets in your GitHub repository:"
          echo "  - AWS_ACCESS_KEY_ID"
          echo "  - AWS_SECRET_ACCESS_KEY"
          echo ""
          echo "To add these secrets:"
          echo "1. Go to your repository Settings > Secrets and variables > Actions"
          echo "2. Click 'New repository secret'"
          echo "3. Add AWS_ACCESS_KEY_ID with your AWS access key"
          echo "4. Add AWS_SECRET_ACCESS_KEY with your AWS secret key"
          exit 1
        fi
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Verify Terraform Directory
      run: |
        if [ ! -d "${{ env.TF_WORKING_DIR }}" ]; then
          echo "❌ Terraform directory '${{ env.TF_WORKING_DIR }}' not found!"
          echo "Expected terraform files in: ${{ env.TF_WORKING_DIR }}/"
          ls -la
          exit 1
        fi
        echo "✅ Terraform directory found: ${{ env.TF_WORKING_DIR }}"

    - name: Bootstrap Terraform Backend
      working-directory: ${{ env.TF_WORKING_DIR }}
      run: |
        echo "🚀 Bootstrapping Terraform backend resources..."
        # Initialize with local backend for bootstrap
        terraform init -backend=false
        # Apply bootstrap configuration to create S3 bucket and DynamoDB table
        terraform apply -target=aws_s3_bucket.terraform_state -target=aws_s3_bucket_versioning.terraform_state -target=aws_s3_bucket_server_side_encryption_configuration.terraform_state -target=aws_dynamodb_table.terraform_locks -auto-approve
        echo "✅ Backend resources created successfully"

    - name: Terraform Init
      working-directory: ${{ env.TF_WORKING_DIR }}
      run: terraform init

    - name: Terraform Apply
      working-directory: ${{ env.TF_WORKING_DIR }}
      run: terraform apply -auto-approve tfplan

  deploy-production:
    runs-on: ubuntu-latest
    needs: terraform-validate
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'production'
    environment: production
    steps:
    - uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Check AWS Credentials
      run: |
        if [ -z "$AWS_ACCESS_KEY_ID" ] || [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
          echo "❌ AWS credentials not found in repository secrets."
          echo "Please configure the following secrets in your GitHub repository:"
          echo "  - AWS_ACCESS_KEY_ID"
          echo "  - AWS_SECRET_ACCESS_KEY"
          echo ""
          echo "To add these secrets:"
          echo "1. Go to your repository Settings > Secrets and variables > Actions"
          echo "2. Click 'New repository secret'"
          echo "3. Add AWS_ACCESS_KEY_ID with your AWS access key"
          echo "4. Add AWS_SECRET_ACCESS_KEY with your AWS secret key"
          exit 1
        fi
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Verify Terraform Directory
      run: |
        if [ ! -d "${{ env.TF_WORKING_DIR }}" ]; then
          echo "❌ Terraform directory '${{ env.TF_WORKING_DIR }}' not found!"
          echo "Expected terraform files in: ${{ env.TF_WORKING_DIR }}/"
          ls -la
          exit 1
        fi
        echo "✅ Terraform directory found: ${{ env.TF_WORKING_DIR }}"

    - name: Bootstrap Terraform Backend
      working-directory: ${{ env.TF_WORKING_DIR }}
      run: |
        echo "🚀 Bootstrapping Terraform backend resources..."
        # Initialize with local backend for bootstrap
        terraform init -backend=false
        # Apply bootstrap configuration to create S3 bucket and DynamoDB table
        terraform apply -target=aws_s3_bucket.terraform_state -target=aws_s3_bucket_versioning.terraform_state -target=aws_s3_bucket_server_side_encryption_configuration.terraform_state -target=aws_dynamodb_table.terraform_locks -auto-approve
        echo "✅ Backend resources created successfully"

    - name: Terraform Init
      working-directory: ${{ env.TF_WORKING_DIR }}
      run: terraform init

    - name: Terraform Apply
      working-directory: ${{ env.TF_WORKING_DIR }}
      run: terraform apply -auto-approve tfplan